# Generated by Django 4.2.7 on 2023-11-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
